# Generated by Django 3.0.7 on 2020-06-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200607_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='suffix',
        ),
    ]
