# Generated by Django 3.0.7 on 2020-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_remove_equipment_suffix"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="suffix",
            field=models.IntegerField(
                choices=[
                    (1, "of Child"),
                    (4, "of Mouse"),
                    (16, "of Minotaur"),
                    (64, "of Dragon"),
                    (256, "of God"),
                    (1024, "of Hamster"),
                ],
                default=1,
            ),
        ),
    ]
